name: Update Hosts File

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours (at 00:00, 12:00 UTC)
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetches the repository files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Use latest Python 3 version

      - name: Install dependencies
        run: pip install requests  # Ensures requests is installed

      - name: Run update script
        run: python update.py  # Executes your Python script

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add openphish_hosts.txt
          git add phishtank_hosts.txt
          git commit -m "Auto-update modified_hosts.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
